# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: health-service-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   ingressClassName: nginx
#   rules:
#     - host: arch.homework
#       http:
#         paths:
#           - path: /otusapp/(.*)/(.*)
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: health-service
#                 port:
#                   number: 80

#           - path: /(.*)
#             pathType: ImplementationSpecific
#             backend:
#               service:
#                 name: health-service
#                 port:
#                   number: 80
# Ingress слушает запросы к arch.homework
# Два правила маршрутизации:
# Прямой доступ: arch.homework/health → сервис
# Rewrite правило: arch.homework/otusapp/aeugene/health → arch.homework/health

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: health-service-ingress
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$2 # REWRITE если ваша проблема решилась регуляркой, то теперь у вас две проблемы (c)
    nginx.ingress.kubernetes.io/rewrite-target: /health/ # REWRITE
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx #класс nginx ingress
  rules:
    - host: arch.homework #хост arch.homework
      http:
        paths:
          - path: /otusapp/([^/]+)/health/?$
            pathType: ImplementationSpecific
            backend:
              service:
                name: health-service
                port:
                  number: 80

          # - path: /health
          #   pathType: Prefix
          - path: /health/?$
            pathType: ImplementationSpecific
            backend:
              service:
                name: health-service
                port:
                  number: 80
